name: Run main
on: push
jobs:
  run:
    name: Job to run main
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - run: go run main.go
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Run tests
        run: go test -v -covermode=count -coverprofile=profile.cov ./...
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: ./profile.cov
