name: Run main
on: push
jobs:
  run:
    name: Job to run main
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - run: go run main.go

